services:
  db:
    image: "postgres:latest"
    command:
      - postgres
      - -c
      - max_locks_per_transaction=1024
      - -c
      - shared_buffers=1GB
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
      - -c
      - max_connections=200
      - -c
      - listen_addresses=*
    environment:
      - "POSTGRES_DB=cards"
      - "POSTGRES_PASSWORD=cards"
      - "POSTGRES_USER=cards"
      - "POSTGRES_HOST=0.0.0.0"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - db
    environment:
      - "DB_HOST=db"
      - "DB_PORT=5432"
      - "DB_NAME=cards"
      - "DB_USER=cards"
      - "DB_PASSWORD=cards"

  web:
    image: nginx:latest
    ports:
      - "8086:80"
    depends_on:
      - app
    volumes:
      - ./dockerfiles/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./web:/usr/share/nginx/html:ro

volumes:
  pgdata:
