package com.darkmusic.aiforgotthesecards.config;

import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.password.PasswordEncoder;

import static org.junit.jupiter.api.Assertions.*;

class BcryptCompatPasswordEncoderTest {

    @Test
    void matchesBcryptjs2bHash() {
        // Generated by bcryptjs with cost 10 for the password "test1234".
        // bcryptjs defaults to the $2b$ prefix.
        String bcryptjsHash = "$2b$10$/YCyTfx4R2/3CMjvt5vK2u/Qxkyuu7dwJlX0MWOFS3cyO1MeLHyF6";

        PasswordEncoder encoder = new BcryptCompatPasswordEncoder();
        assertTrue(encoder.matches("test1234", bcryptjsHash));
        assertFalse(encoder.matches("wrong", bcryptjsHash));
    }
}
